name: Package

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/**
      - .gitignore
      - .gitattributes
      - LICENSE.txt
      - README.md
  pull_request:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Package mod
        run: |
          mkdir AidenHelper
          mkdir AidenHelper/Code
          mv Loenn/ AidenHelper/
          mv Graphics/ AidenHelper/
          cp bin/Debug/AidenHelper.dll AidenHelper/Code/
          cp everest.yaml AidenHelper/

      - name: Update everest.yaml DLL location
        run: ./replace-dll-location.sh AidenHelper/everest.yaml

      - name: zip AidenHelper
        run: zip -r AidenHelper.zip AidenHelper

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: AidenHelper.zip
          path: ./AidenHelper.zip
